### PR TITLE
SettingsScreen to stateful, conflicts fix, minor issues fixed

### LINKED ISSUE #89: Ads are not served sometimes
If ads has not been served, a card should be revealed immediately after the error callback received

### PR DESCRIPTION
**Pull request by bgoncharuck**
- Changed SettingsScreen to stateful
- Fixed conflicts between previous pull requests
- Found and solved typos and minor issues
- Tested in profile mode, works and starts much better and cached correctly, thank you @rimmer 

Also a problem. I can't load the production ad

### CODE REVIEW

File: packages/mobile_app/lib/common/precache_assets.dart [hunk 1]
```diff
@@ -17,30 +17,29 @@ class PrecacheAssets {
...
-      },
-      for (var i = 1; i < 10; i++) {
-        svg["$i.svg"] = images[_cardsAssets.length + i - 1]
-      }
-    });
+          for (var i = 0; i < _cardsAssets.length; i++)
+            {svg[_cardsAssets[i]] = images[i]},
+          for (var i = 1; i < 10; i++)
+            {svg["$i.svg"] = images[_cardsAssets.length + i - 1]}
+        });
```
Comment (rimmer) [inline packages/mobile_app/lib/common/precache_assets.dart:42]: Not sure this formatting is better. Have u used autoformat?

File: packages/mobile_app/lib/app_global.dart [hunk 2]
```diff
@@ -69,8 +69,8 @@ class _Firebase {
 
 class _Ads {
   AdManagerInterstitialAd manager;
-  bool adsWatched = false;
-  bool adsLoaded = false;
+  bool adsAreWatched = false;
+  bool adsAreLoaded = false;
```
Comment (rimmer) [inline packages/mobile_app/lib/app_global.dart]: `AreWatched` — this form still does not correspond to what it does. correctly it would haveBeenWatched but it is very long. so I simplified

File: packages/mobile_app/lib/main.dart [hunk 3]
```diff
@@ -6,10 +6,10 @@ void main() async {
   WidgetsFlutterBinding.ensureInitialized();
 
   // Measure startup time
-  Stopwatch initTime = Stopwatch()..start();
+  // Stopwatch initTime = Stopwatch()..start();
```
Comment (rimmer) [inline packages/mobile_app/lib/main.dart]: I would rather remove it instead of commenting out

File: packages/mobile_app/lib/main.dart [hunk 4]
```diff
@@ -63,10 +63,11 @@ void main() async {
 
   await Future.wait([
     notificationFuture,
-    assets
+    assets,
+    initAd,
```
Comment (rimmer) [inline packages/mobile_app/lib/main.dart]: I disagree we need to wait for an ad to be loaded before start drawing

File: packages/mobile_app/lib/main.dart [hunk 5]
```diff
@@ -63,10 +63,11 @@ void main() async {
...
   ]);
 
-  print("Initialization took ${initTime.elapsed}");
+  // print("Initialization took ${initTime.elapsed}");
```
Comment (rimmer) [inline packages/mobile_app/lib/main.dart]: Can be also removed

**Review by rimmer — CHANGES_REQUESTED** [review]

File: packages/mobile_app/lib/main.dart (hunk 4 above)
Comment (bgoncharuck) [reply packages/mobile_app/lib/main.dart]: Nothing is drawn before BuildContext (elements tree) is created.

File: packages/mobile_app/lib/common/precache_assets.dart (hunk 1 above)
Comment (bgoncharuck) [reply packages/mobile_app/lib/common/precache_assets.dart:42]: I do, a Dart package for VSCode has it by default as far as I know.

**Review by rimmer — APPROVED** [review]
A side note: dart formatter does not a  great job on autoformatting :/
