### PR TITLE
Prediction fixes

### LINKED ISSUE #89: Ads are not served sometimes
If ads has not been served, a card should be revealed immediately after the error callback received

### PR DESCRIPTION
**Pull request by bgoncharuck**
- **Added private submodule for language specific texts**
- **Fixed ads issue #89** , close #89
- **Changed script, to work in more difficult conditions**
- Added and tested fully working english version of app
- Added platform specific choice of language
- **Added custom user interaction for language choice**
- Added and tested new russian predictions
- _Texts submodule has started work on sql db. (in separate branch)_

### CODE REVIEW

File: packages/mobile_app/lib/screens/daily/screen/methods/cards.dart [hunk 1]
```diff
@@ -36,16 +36,17 @@ extension DailyScreenCardsMethods on _DailyScreenState {
...
-                                  ? () {}
-                                  : () {
-                                      onWatchAdsClick();
-                                    },
+                              onButtonTap:
+                                  (StaticProvider.ads.watchAdsButtonIsInactive)
+                                      ? () {}
+                                      : () {
+                                          adsOnInternetAvailable();
+                                        },
```
Comment (rimmer) [inline packages/mobile_app/lib/screens/daily/screen/methods/cards.dart:49]: Nit: possible to pass a function like a closure? 
```dart
: adsOnInternetAvailable();
```

**Review by rimmer — APPROVED** [review]
